use rsfaccar
go


DELETE CO0001MOVD WHERE YEAR(OC_DFECDOC) < 2017
GO
DELETE CO0001MOVC WHERE YEAR(OC_DFECDOC) < 2017
GO
DELETE AL0001MOVD WHERE YEAR(C6_DFECDOC) < 2017
GO
DELETE AL0001MOVC WHERE YEAR(C5_DFECDOC) < 2017
GO
DELETE FT0001facd
GO
DELETE FT0001FACC 
GO
DELETE FT0001ACUD WHERE YEAR(F6_DFECDOC) < 2017
GO
DELETE FT0001ACUC WHERE YEAR(F5_DFECDOC) < 2017

USE  rsfaccar;
GO
-- Truncate the log by changing the database recovery model to SIMPLE.
ALTER DATABASE rsfaccar
SET RECOVERY SIMPLE;
GO
-- Shrink the truncated log file to 1 MB.
DBCC SHRINKFILE (rsfaccar_LOG, 1);
GO
-- Reset the database recovery model.
ALTER DATABASE rsfaccar
SET RECOVERY FULL;
GO