--SELECT top 30 * from ASIGNA_CCT WHERE cli = '00001' ORDER BY cct 


SELECT * FROM CCTELA WHERE CCT = '0000003893'



SELECT DISTINCT 
    cc.PARTIDA AS PAR, cc.TELA AS TEL,CC.COLOR, CC.TELA+CC.COLOR+CC.COMBI AS XX,
	(SELECT AR_CDESCRI FROM RSFACCAR..AL0001ARTI WHERE AR_CCODIGO COLLATE SQL_Latin1_General_CP1_CI_AI= CC.TELA+CC.COLOR+CC.COMBI) AS DESTELA,
	cc.CLIENTE AS CLI, 
    cl.NOMBRE AS DESCLI, cc.COLOR AS COL, kk.DESCRIPCION AS DESCOL, CONVERT(nVARCHAR(max), cc.fecini, 103)  AS FEC, 
    cc.PROVEEDOR AS RUC, (SELECT AC_CNOMBRE FROM RSCONCAR..CP0001MAES Where AC_CVANEXO='P' 
	And AC_CCODIGO= CC.PROVEEDOR COLLATE SQL_Latin1_General_CP1_CI_AI) AS PROVEE,  
	ROUND(cc.PESOTOTAL, 3) AS KGS,    cc.CALIDAD AS CAL, cc.CONDICION AS CON,  cc.TOTALROLLOS AS RLL,cc.CCT
FROM     dbo.CCTELA as cc 
INNER JOIN		 TELAS   as tt ON cc.TELA    = tt.TELA 
INNER JOIN		 CLIENTE as cl ON cc.CLIENTE = cl.CODIGO 
INNER JOIN		 COLORES as kk ON cc.COLOR   = kk.CODIGO 
LEFT OUTER JOIN   VIEW_PARTIDAS as vp ON cc.PROVEEDOR = vp.RUC COLLATE SQL_Latin1_General_CP1_CI_AI AND 
                cc.PARTIDA COLLATE Modern_Spanish_CI_AS = vp.PARTIDA
WHERE CALIDAD = 1  AND YEAR(cc.FECHA) >= 2018 AND cc.ESTADO = 'A' AND CC.PARTIDA = '29670'
