-- COLORES DE COMBOS DEL CLIENTE, TEMPORADA, ESTILO QUE TIENEN EXPLOSION DE TELA
select  DISTINCT -- VP.po, VP.cli, VP.codest,VP.temporada, 
ET.COMBO--, ET.TELA
FROM VIEW_POS as vp
inner join EXPLOSION_TELA as ET ON ET.OFI=VP.OFI AND ET.PO = VP.PO
INNER JOIN PO_PARTIDA AS PPO ON PPO.PO = ET.PO
INNER JOIN ASIGNA_CCT AS ACC ON ACC.CCT = PPO.CCT
where vp.cli = '00001' and vp.codest= '00002' and vp.temporada = '035'

--SELECT * FROM ESTILOS WHERE CLIENTE = '00001' AND ESTCLI = '540291'
--SELECT DISTINCT PO  FROM  PO_PARTIDA

SELECT DISTINCT VP.PO, PDD.COLOR
FROM		VIEW_POS		AS VP 
INNER JOIN	[PO-DETA]		AS PDD ON PDD.PO = VP.PO
INNER JOIN  PO_PARTIDA		AS PPO ON PPO.PO = PDD.PO AND PDD.UBI = PPO.ubi
inner join  EXPLOSION_TELA	as ET ON ET.OFI=VP.OFI AND ET.PO = VP.PO
INNER JOIN	CCTELA			AS CCT ON CCT.CCT = PPO.CCT  AND ET.TELA= CCT.TELA + CCT.COLOR + CCT.COMBI 
WHERE VP.CODEST = '00006' AND VP.TEMPORADA = '035' AND VP.CLI = '00001'
