
Select A.C5_CALMA AS Alm, A.C5_CCODMOV AS Mov, A.C5_CTD AS TD, A.C5_CNUMDOC AS NUM_DOC ,  A.C5_DFECDOC AS Fec_Doc, C5_CRFNDOC AS Doc_Ref, CP_CNUMDOC as Factura, C5_CGLOSA1 AS Glosa,  C5_DFECCRE AS Fec_Crea, C5_CUSUCRE AS Usr_Crea, c5_CSITUA AS SIT ,C5_CNUMORD ,MONTO, C6_CCODIGO,(C6_NCANTID) AS QTY, C6_NPREUN1 AS UNITARIO, (C6_NVALTOT) AS TOTAL, C6_CNUMDOC as parte
From RSFACCAR..AL0001MOVC A  
LEFT JOIN MULTI..RS_ALMOVC0001 B ON(A.C5_CALMA collate SQL_Latin1_General_CP1_CI_AI=B.C5_CALMA 
AND A.C5_CTD  collate SQL_Latin1_General_CP1_CI_AI=B.C5_CTD AND A.C5_CNUMDOC collate SQL_Latin1_General_CP1_CI_AI=B.C5_CNUMDOC) 
INNER JOIN RSFACCAR..AL0001MOVD D ON A.C5_CALMA = C6_CALMA AND A.C5_CNUMDOC= C6_CNUMDOC
INNER JOIN RSFACCAR..CONSOLIDADO_RHIN AS R ON FACTURA  collate SQL_Latin1_General_CP1_CI_AI = CP_CNUMDOC collate SQL_Latin1_General_CP1_CI_AI

--INNER JOIN RSCONCAR..CP0001CART AS X ON RUC=CP_CCODIGO AND FACTURA=CP_CNUMDOC
--WHERE A.C5_CNUMORD ='0000031905' AND CP_CNUMDOC = '001-16198'
WHERE A.C5_CALMA='00R2' AND A.C5_CNUMDOC = '00017300172'
ORDER BY A.C5_CTD+A.C5_CNUMDOC 