USE MODELADOR
GO

CREATE TABLE [dbo].[OCTALLA](
	[NUMORD]	char(8) NOT NULL ,
	[ITEM]		CHAR(20) NOT NULL DEFAULT '',
	[T0]		CHAR(5) NOT NULL DEFAULT '',
	[Q0]		FLOAT NOT NULL DEFAULT 0,
	[T1]		CHAR(5) NOT NULL DEFAULT '',
	[Q1]		FLOAT NOT NULL DEFAULT 0,
	[T2]		CHAR(5) NOT NULL DEFAULT '',
	[Q2]		FLOAT NOT NULL DEFAULT 0,
	[T3]		CHAR(5) NOT NULL DEFAULT '',
	[Q3]		FLOAT NOT NULL DEFAULT 0,
	[T4]		CHAR(5) NOT NULL DEFAULT '',
	[Q4]		FLOAT NOT NULL DEFAULT 0,
	[T5]		CHAR(5) NOT NULL DEFAULT '',
	[Q5]		FLOAT NOT NULL DEFAULT 0,
	[T6]		CHAR(5) NOT NULL DEFAULT '',
	[Q6]		FLOAT NOT NULL DEFAULT 0,
	[T7]		CHAR(5) NOT NULL DEFAULT '',
	[Q7]		FLOAT NOT NULL DEFAULT 0,
	[T8]		CHAR(5) NOT NULL DEFAULT '',
	[Q8]		FLOAT NOT NULL DEFAULT 0,
	[T9]		CHAR(5) NOT NULL DEFAULT '',
	[Q9]		FLOAT NOT NULL DEFAULT 0,
	[KGUNI]		NUMERIC(18,3) NOT NULL DEFAULT 0,
	[USUARIO]	CHAR(10),
	[FECHA]		[SMALLdatetime] DEFAULT GETDATE(),
	[ESTADO]	CHAR(1) DEFAULT 'A',
	 CONSTRAINT [PK_octal] PRIMARY KEY CLUSTERED 
(	[NUMORD]	ASC,
	[ITEM]		ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

