USE MODELADOR
GO
--DROP TABLE  PO_PARTIDA
GO

CREATE TABLE [dbo].PO_PARTIDA (
	[PO]		char(20) NOT NULL  ,
	[CCT]		CHAR(10)  NOT NULL DEFAULT '',
	[ubi]		int  NOT NULL DEFAULT 0,
	[KGS]		NUMERIC(18,3) NOT NULL DEFAULT 0,
	[CANT]		INTEGER NOT NULL DEFAULT 0,
	[OCORTE]	CHAR(10) NOT NULL DEFAULT '',
	[OSERV]		CHAR(13) NOT NULL DEFAULT '',
	[USUARIO]	CHAR(10),
	[FECHA]		[SMALLdatetime] DEFAULT GETDATE(),
	[ESTADO]	CHAR(1) DEFAULT 'A',
	 CONSTRAINT [PK_POPAR] PRIMARY KEY CLUSTERED 
(	[PO]	ASC,
	[CCT]		ASC,
	[ubi]	asc
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


update CCTELA set saldo = PESOTOTAL
--SELECT * FROM EXPLOSION_TELA WHERE TELA = '6000000999000400'
-- QTY DE EXPLOSION TELA YA TIENE EL 5% ADICIONAL
-- EXPLOSION_TELA TIENE UNA COLUMNA QUE SE LLAMA OSCORTE