--EXEC SP_COMBOS_PARTIDA '00001', '00006', '035' 
declare @cli char(5)
declare @est char(5)
declare @tem char(3)
set @cli = '00001'
set @est = '00006'
set @tem= '035'
	
--select * from explosion_tela where po = '218-665'

SELECT DISTINCT ET.COMBO, ET.UBI, PPO.CCT,  ET.TELA AS TELA, ET.COLPZA, ET.PO
INTO #TMP1
FROM     dbo.CCTELA AS CCT 
INNER JOIN			PO_PARTIDA		AS PPO ON CCT.CCT = PPO.CCT 
RIGHT OUTER JOIN	EXPLOSION_TELA	AS ET  ON CCT.TELA + CCT.COLOR + CCT.COMBI = ET.TELA AND PPO.PO = ET.PO AND PPO.ubi = ET.UBI 
LEFT OUTER JOIN		VIEW_POS		AS vp  ON ET.PO = vp.PO
WHERE  (vp.CLI = @CLI) AND (vp.CODEST = @EST) AND (vp.TEMPORADA = @TEM) AND NOT LEFT(ET.TELA,1) = '9'



SELECT DISTINCT ET.COMBO, ET.UBI, PPO.CCT,  ET.TELA AS TELA, ET.COLPZA, ET.PO
INTO #TMP2
FROM     dbo.CCTELA AS CCT 
INNER JOIN			PO_PARTIDA		AS PPO ON CCT.CCT = PPO.CCT 
RIGHT OUTER JOIN	EXPLOSION_TELA	AS ET  ON CCT.TELA + CCT.COLOR + CCT.COMBI = ET.TELA AND PPO.PO = ET.PO AND PPO.ubi = ET.UBI 
LEFT OUTER JOIN		VIEW_POS		AS vp  ON ET.PO = vp.PO
WHERE  (vp.CLI = @CLI) AND (vp.CODEST = @EST) AND (vp.TEMPORADA = @TEM) AND NOT LEFT(ET.TELA,1) = '9'
AND NOT PPO.CCT IS NULL


SELECT DISTINCT COMBO FROM #TMP2 
WHERE #TMP2.COMBO+#TMP2.CCT NOT IN (SELECT #TMP1.COMBO+#TMP1.CCT FROM #TMP1 WHERE #TMP1.CCT IS NULL )

select DISTINCT A2.COMBO ,A2.colpza, A2.PO, A1.CCT from #tmp1 AS A1 
INNER JOIN #TMP2 AS A2 ON A1.COMBO=A2.COMBO AND A1.UBI = A2.UBI AND A1.COLPZA=A2.COLPZA AND A1.CCT = A2.CCT
--where A2.PO = '218-665' 
--select * from #tmp2
SELECT DISTINCT COMBO, colpza, PO FROM #TMP2 WHERE   COMBO IN (SELECT COMBO FROM #TMP1 WHERE #TMP1.CCT IS NULL)
select * from view_po_partida where po IN ('218-665','219-62')
/*
DROP TABLE #TMP1
DROP TABLE #TMP2
*/



