SELECT ET.TELA, AR_CDESCRI , ET.ubi, qty,
T0,T1,T2,T3,T4,T5,T6,T7,T8,T9, C0,C1,C2,C3,C4,C5,C6,C7,C8,C9,*
FROM VIEW_EXPLOSION_TELAS AS ET
INNER JOIN RSFACCAR..AL0001ARTI AS AR ON ET.TELA COLLATE Modern_Spanish_CI_AS= AR_CCODIGO
inner join VIEW_PO_DETA_105 as vp ON VP.PO=ET.PO AND VP.UBI = ET.UBI 
WHERE ET.PO = '219-332' AND REPLACE(COMBO,' ' , '') = 'NAUTICALBLUE778' 
ORDER BY ET.TELA

SELECT sum(cant) as cant, sum(kgs) as kgs , replace(tela+color+combi,' ' , '') as tela 
FROM dbo.CCTELA AS CCT 
INNER JOIN			PO_PARTIDA		AS PPO ON CCT.CCT = PPO.CCT 
where po = '219-332' and  replace(tela+color+combi,' ' , '')  in (select tela from VIEW_EXPLOSION_TELAS WHERE PO = '219-332' AND REPLACE(COMBO,' ' , '') = 'NAUTICALBLUE778' and ubi = 30)
AND UBI = 30
group by  replace(tela+color+combi,' ' , '') 





-- DEVUELVE LAS PO'S COMPLETAS DE ESA TEMPORADA, ESTILO, CLIENTE, COMBO
EXEC SP_DESPACHO_PARTIDAS_combo'00001', '00006', '035' , 'NAUTICALBLUE778'

-- DEVUELVE EL DETALLE DE TELA/PARTIDA, RECITLINEOS POR CADA PO DEL SP ANTERIOR
EXEC SP_DESPACHO_PARTIDAS_PO'00001', '00006', '035' , 'NAUTICALBLUE778' , '219-332'

SELECT  TOP 1 ET.PO,ET.ubi, 
T0,T1,T2,T3,T4,T5,T6,T7,T8,T9, C0,C1,C2,C3,C4,C5,C6,C7,C8,C9, 
(C0+C1+C2+C3+C4+C5+C6+C7+C8+C9) AS TOT, qty, VPP.CANT
FROM VIEW_EXPLOSION_TELAS AS ET
inner join VIEW_PO_DETA_105 as vp ON VP.PO=ET.PO AND VP.UBI = ET.UBI 
INNER JOIN VIEW_PO_PARTIDA AS VPP ON VPP.PO = ET.PO AND VPP.ubi = ET.UBI
WHERE ET.PO = '219-332' AND REPLACE(COMBO,' ' , '') = 'NAUTICALBLUE778'  AND ET.CLI = '00001' AND ET.ESTILO = '00006' AND ET.TEMPORADA ='035'
order by ET.tela
