select * from  explosion_tela

EXEC sp_rename 'EXPLOSION_TELA.OCH1', 'OSCORTE', 'COLUMN';
EXEC sp_rename 'EXPLOSION_TELA.OCH2', 'OSCOSTU', 'COLUMN';
EXEC sp_rename 'EXPLOSION_TELA.OCH3', 'OSACABA', 'COLUMN';
EXEC sp_rename 'EXPLOSION_TELA.OCH4', 'OSBORDA', 'COLUMN';
EXEC sp_rename 'EXPLOSION_TELA.OCH5', 'OSESTAM', 'COLUMN';
EXEC sp_rename 'EXPLOSION_TELA.OCH6', 'OSLAVAD', 'COLUMN';

ALTER TABLE EXPLOSION_TELA
DROP COLUMN OCTELA
GO
ALTER TABLE EXPLOSION_TELA
DROP COLUMN OCTEJE
GO
ALTER TABLE EXPLOSION_TELA
DROP COLUMN OCTINTO
GO
ALTER TABLE EXPLOSION_TELA
DROP COLUMN OCACABA
GO