USE MODELADOR 
GO

-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ============================================================================
-- Author:		Mabel Molina
-- Create date: 30-10-2008
-- Description:	Devuelve las PARTIDAS ASIGNADAS A LOS Combos que tienen
--				partida asignada con colores completos
-- ============================================================================
--DROP PROCEDURE SP_DESPACHO_PARTIDAS_COMBO

alter PROCEDURE SP_DESPACHO_PARTIDAS_COMBO
	
@cli char(5),
@est char(5),
@tem char(3),
@COM CHAR(200)

AS

set nocount on

BEGIN
SELECT DISTINCT ET.COMBO, ET.UBI, PPO.CCT,  ET.TELA AS TELA, ET.COLPZA, et.QTY, ppo.CANT, et.po, PPO.KGS
INTO #TMP1
FROM     dbo.CCTELA AS CCT 
INNER JOIN			PO_PARTIDA		AS PPO ON CCT.CCT = PPO.CCT 
RIGHT OUTER JOIN	EXPLOSION_TELA	AS ET  ON CCT.TELA + CCT.COLOR + CCT.COMBI = ET.TELA AND PPO.PO = ET.PO AND PPO.ubi = ET.UBI 
LEFT OUTER JOIN		VIEW_POS		AS vp  ON ET.PO = vp.PO
WHERE  (vp.CLI = @cli) AND (vp.CODEST = @est) AND (vp.TEMPORADA = @tem) AND NOT LEFT(ET.TELA,1) = '9'


--SELECT * FROM PO_PARTIDA
SELECT DISTINCT ET.COMBO, ET.UBI, PPO.CCT,  ET.TELA AS TELA, ET.COLPZA, et.QTY, ppo.CANT,et.po, PPO.KGS
INTO #TMP2
FROM     dbo.CCTELA AS CCT 
INNER JOIN			PO_PARTIDA		AS PPO ON CCT.CCT = PPO.CCT 
RIGHT OUTER JOIN	EXPLOSION_TELA	AS ET  ON CCT.TELA + CCT.COLOR + CCT.COMBI = ET.TELA AND PPO.PO = ET.PO AND PPO.ubi = ET.UBI 
LEFT OUTER JOIN		VIEW_POS		AS vp  ON ET.PO = vp.PO
WHERE  (vp.CLI = @cli) AND (vp.CODEST = @est) AND (vp.TEMPORADA = @tem) AND NOT LEFT(ET.TELA,1) = '9'
AND NOT PPO.CCT IS NULL


select DISTINCT A2.COMBO, A2.UBI, A2.CCT, A2.TELA, A2.COLPZA, A2.QTY, A2.CANT, A2.PO, A2.KGS 
INTO #TMP3  
from #tmp1 AS A1 
INNER JOIN #TMP2 AS A2 ON A1.COMBO=A2.COMBO AND A1.UBI = A2.UBI AND A1.COLPZA=A2.COLPZA AND A1.CCT = A2.CCT


SELECT * INTO #TMP4 FROM (
SELECT * FROM #TMP3
UNION
SELECT VP.COMBO, VP.UBI, '' AS CCT, VP.TELA, VP.COLPZA, 0 AS QTY0, VP.QTY, VP.PO, VP.KGS
FROM VIEW_EXPLOSION_TELAS AS VP 
INNER JOIN  #TMP3 AS A3 ON A3.PO = VP.PO AND  VP.COMBO = A3.COMBO
WHERE  (vp.CLI = @cli) AND (vp.ESTILO = @est) AND (vp.TEMPORADA = @tem) AND  LEFT(VP.TELA,1) = '9'
)MM


SELECT T1.PO, T1.COMBO, T1.UBI, T1.CCT, T1.COLPZA, T1.TELA, AR_CDESCRI, T1.CANT, T1.KGS , ISNULL(CC.PARTIDA,'') AS PARTIDA
FROM #TMP4 AS T1
INNER JOIN RSFACCAR..AL0001ARTI ON AR_CCODIGO COLLATE SQL_Latin1_General_CP1_CI_AI = TELA
LEFT OUTER JOIN CCTELA AS CC ON CC.CCT = T1.CCT
WHERE REPLACE(COMBO,' ' , '') = REPLACE(@COM, ' ' , '')
ORDER BY  PO, COMBO, TELA

DROP TABLE #TMP1
DROP TABLE #TMP2
DROP TABLE #TMP3
DROP TABLE #TMP4
END
