USE MODELADOR
GO
drop table servitmp
go
DROP TABLE [SERVITALLA]
go
DROP TABLE [SERVIdet]
GO
DROP TABLE [SERVITELAS]
GO
CREATE TABLE [dbo].[SERVIDET](
	 [NUMORD]	char(14) NOT NULL ,
	 [LIN]		CHAR(2)  NOT NULL DEFAULT '01',
	 [PO]		CHAR(20) NOT NULL DEFAULT '',
	 [UBI]		INT NOT NULL DEFAULT 1,
	 [Q0]		INT  NOT NULL DEFAULT 0,
	 [Q1]		INT  NOT NULL DEFAULT 0,
	 [Q2]		INT  NOT NULL DEFAULT 0,
	 [Q3]		INT  NOT NULL DEFAULT 0,
	 [Q4]		INT  NOT NULL DEFAULT 0,
	 [Q5]		INT  NOT NULL DEFAULT 0,
	 [Q6]		INT  NOT NULL DEFAULT 0,
	 [Q7]		INT  NOT NULL DEFAULT 0,
	 [Q8]		INT  NOT NULL DEFAULT 0,
	 [Q9]		INT  NOT NULL DEFAULT 0,
	 [T0]		CHAR(5) NOT NULL DEFAULT '',
	 [T1]		CHAR(5) NOT NULL DEFAULT '',
	 [T2]		CHAR(5) NOT NULL DEFAULT '',
	 [T3]		CHAR(5) NOT NULL DEFAULT '',
	 [T4]		CHAR(5) NOT NULL DEFAULT '',
	 [T5]		CHAR(5) NOT NULL DEFAULT '',
	 [T6]		CHAR(5) NOT NULL DEFAULT '',
	 [T7]		CHAR(5) NOT NULL DEFAULT '',
	 [T8]		CHAR(5) NOT NULL DEFAULT '',
	 [T9]		CHAR(5) NOT NULL DEFAULT '',
	 CONSTRAINT PK_SERVIDET PRIMARY KEY (NUMORD,LIN,PO,UBI)
) ON [PRIMARY]


CREATE TABLE [dbo].[SERVITELAS](
	 [NUMORD]	char(14) NOT NULL ,
	 [LIN]		CHAR(2)  NOT NULL DEFAULT '01',
	 [PO]		CHAR(20) NOT NULL DEFAULT '',
	 [UBI]		INT		 NOT NULL DEFAULT 1,
	 [ITEM]		CHAR(2)  NOT NULL DEFAULT '01',
	 [TELA]		CHAR(6)  NOT NULL DEFAULT '',
	 [PARTIDA]	CHAR(15) NOT NULL DEFAULT '',
	 [KGS]		NUMERIC (18,3) NOT NULL DEFAULT 0,
	 [QTY]		INT		 NOT NULL DEFAULT 0,
CONSTRAINT PK_SERVITEL PRIMARY KEY (NUMORD,LIN,PO,UBI, ITEM)
) ON [PRIMARY]
