CREATE view VIEW_LIQUIDA 
AS
SELECT OC_CNUMORD AS NRO_OC,OC_CCODPRO as RUC,  CONVERT(VARCHAR, OC_DFECDOC, 103) AS FECHA, 
	OC_CRAZSOC AS PROVEEDOR, OC_CTIPORD AS TIP,
OC_CCODMON AS MON, 
CASE WHEN oc_ccodmon = 'MN' THEN oc_nimpMN ELSE oc_nimpus END AS IMPORTE,
 OC_CSITORD AS SIT,
(SELECT TG_CDESCRI FROM      RSFACCAR.dbo.AL0001TABL WHERE (TG_CCOD = '31') 
	AND (RSFACCAR.dbo.CO0001MOVC.OC_CSITORD = TG_CCLAVE)) AS ESTADO, 
	 OC_CCOTIZA AS COTIZA
FROM     RSFACCAR.dbo.CO0001MOVC
WHERE  (YEAR(OC_DFECDOC) > 2017) AND (OC_CSITORD IN ('5'))
/*
SELECT TG_CCLAVE,TG_CDESCRI FROM      RSFACCAR.dbo.AL0001TABL WHERE (TG_CCOD = '31') 
SELECt OC_CESTADO,* FROM RSFACCAR..CO0001MOVD WHERE OC_CNUMORD = '0000030485'
SELECt OC_CSITORD,* FROM RSFACCAR..CO0001MOVC WHERE OC_CNUMORD = '0000030485'
update RSFACCAR..CO0001MOVC set oc_dfecdoc = getdate()  WHERE OC_CNUMORD = '0000030485'
*/