USE MODELADOR
GO
ALTER VIEW VIEW_EXPLOSION_TELAS
AS
SELECT        ET.OFI, ET.PO, ET.TELA, ET.QTY, ET.KGS, VP.ESTILO, VP.ESTCLI, VP.TEMPORADA, VP.DESTEM, VP.CLI, VP.NOM, ET.UBI, ET.ID, ET.COMBO, ET.ETC, ET.COLPZA, 
                         ET.CRUDO, VP.CODARTICULO, ET.KGSTEJE, ET.H1, ET.H2, ET.H3, ET.H4, ET.H5, ET.H6, ET.P1, ET.P2, ET.P3, ET.P4, ET.P5, ET.P6, ET.K1, ET.K2, ET.K3, ET.K4, 
                         ET.K5, ET.K6, VP.FECHA
FROM            dbo.EXPLOSION_TELA AS ET 
INNER JOIN      dbo.VIEW_POS AS VP ON ET.PO = VP.PO AND ET.OFI = VP.OFI


