alter view view_ofi_deta_telas
as

SELECT DISTINCT 
    TOP (100) PERCENT OP.OFI, PP.PO, PP.COLOR AS COMBO, PP.UBI, PD.ID, PD.CODIGO AS tela, FT.DESCRIPCION AS FAMTEL, PD.ADICIONAL AS OBS, 
    ceiling(  SUM(PP.CAN0 * dbo.porcentaje(CC.COBERTURA)) + SUM(PP.CAN1 * dbo.porcentaje(CC.COBERTURA)) + SUM(PP.CAN2 * dbo.porcentaje(CC.COBERTURA)) 
    + SUM(PP.CAN3 * dbo.porcentaje(CC.COBERTURA)) + SUM(PP.CAN4 * dbo.porcentaje(CC.COBERTURA)) + SUM(PP.CAN5 * dbo.porcentaje(CC.COBERTURA)) 
    + SUM(PP.CAN6 * dbo.porcentaje(CC.COBERTURA)) + SUM(PP.CAN7 * dbo.porcentaje(CC.COBERTURA)) + SUM(PP.CAN8 * dbo.porcentaje(CC.COBERTURA)) 
    + SUM(PP.CAN9 * dbo.porcentaje(CC.COBERTURA))) AS QTY,
	SUM((PP.CAN0 * dbo.porcentaje(CC.COBERTURA )) * PD.PESO / 1000) 
    + SUM((PP.CAN1 * dbo.porcentaje(CC.COBERTURA )) * PD.PESO / 1000) + SUM((PP.CAN2 * dbo.porcentaje(CC.COBERTURA )) * PD.PESO / 1000) 
    + SUM((PP.CAN3 * dbo.porcentaje(CC.COBERTURA )) * PD.PESO / 1000) + SUM((PP.CAN4 * dbo.porcentaje(CC.COBERTURA )) * PD.PESO / 1000) 
    + SUM((PP.CAN5 * dbo.porcentaje(CC.COBERTURA )) * PD.PESO / 1000) + SUM((PP.CAN6 * dbo.porcentaje(CC.COBERTURA )) * PD.PESO / 1000) 
    + SUM((PP.CAN7 * dbo.porcentaje(CC.COBERTURA )) * PD.PESO / 1000) + SUM((PP.CAN8 * dbo.porcentaje(CC.COBERTURA )) * PD.PESO / 1000) 
    + SUM((PP.CAN9 * dbo.porcentaje(CC.COBERTURA )) * PD.PESO / 1000) AS KILOS, PRO.CLIENTE, PRO.ESTILO, PRO.TEMPORADA, dbo.ETC.CODETC, 
    CASE WHEN LEFT(pd.codigo, 1) = '9' THEN PD.CANPZA ELSE 1 END AS CANPZA
FROM     dbo.[PO-DETA] AS PP INNER JOIN
    dbo.POS ON dbo.POS.PO = PP.PO INNER JOIN
    dbo.COTIZACION AS CC ON CC.COTIZACION = dbo.POS.COTIZACION INNER JOIN
    dbo.AJUSTES AS PRO ON CC.PROTO = PRO.AJUSTE AND CC.VERSION = PRO.VERSION INNER JOIN
    dbo.[AJUSTE-DETALLES] AS PD ON PRO.AJUSTE = PD.AJUSTE AND PRO.VERSION = PD.VERSION INNER JOIN
    dbo.OFI_POS AS OP ON OP.PO = dbo.POS.PO INNER JOIN
    dbo.FAMTELAS AS FT ON LEFT(FT.CORREL, 2) = LEFT(PD.CODIGO, 2) INNER JOIN
    dbo.ETC ON PRO.CLIENTE = dbo.ETC.CODCLI AND PRO.ESTILO = dbo.ETC.CODEST AND PRO.TEMPORADA = dbo.ETC.CODTEM
WHERE  (PD.TIPODETALLE = 'TE') AND (PP.ESTADO = 'A')
GROUP BY PP.COLOR, PD.ID, PD.ADICIONAL, FT.DESCRIPCION, OP.OFI, PD.CODIGO, PP.PO, PP.UBI, PRO.CLIENTE, PRO.ESTILO, PRO.TEMPORADA, dbo.ETC.CODETC, PD.CANPZA