CREATE VIEW dbo.VIEW_SERVICIO_TALLERES
AS
SELECT TOP 100 PERCENT numord AS NRO_DOC, 
            CONVERT(VARCHAR, FECDOC, 103) AS FECHA, 
            ac_cnombre AS PROVEEDOR, 
            codmon AS Mon, 
            IMPORTE = CASE WHEN codmon = 'MN' THEN impMN ELSE impus END, 
     ( SELECT TG_CDESCRI
       FROM RSFACCAR..AL0001TABL
       WHERE TG_CCOD = '31' AND SITORD COLLATE Modern_Spanish_CI_AS = TG_CCLAVE COLLATE Modern_Spanish_CI_AS
     ) AS EDO, 
            SITORD AS SIT, 
            CODIGO, 
            DESCRIPCION AS TIPSER
     FROM MODELADOR..SERVICAB
          INNER JOIN RSCONCAR..CP0001MAES ON AC_CCODIGO COLLATE Modern_Spanish_CI_AS = RUC COLLATE Modern_Spanish_CI_AS
          INNER JOIN TIPSERV ON TIPSER = CODIGO
     WHERE AC_CVANEXO = 'P'
     ORDER BY 1 DESC;
