CREATE VIEW VIEW_OC_TOTAL
AS

SELECT OC_CNUMORD AS NRO_OC, OC_CCODPRO AS RUC, CONVERT(VARCHAR, OC_DFECDOC, 103) AS FECHA, OC_CRAZSOC AS PROVEEDOR, OC_CTIPORD AS TIP, 
                  OC_CCODMON AS MON, CASE WHEN oc_ccodmon = 'MN' THEN oc_nimpMN ELSE oc_nimpus END AS IMPORTE, OC_CSITORD AS SIT,
                      (SELECT TG_CDESCRI
                       FROM      RSFACCAR.dbo.AL0001TABL
                       WHERE   (TG_CCOD = '31') AND (RSFACCAR.dbo.CO0001MOVC.OC_CSITORD = TG_CCLAVE)) AS ESTADO, OC_CCOTIZA AS COTIZA
FROM     RSFACCAR.dbo.CO0001MOVC
UNION
SELECT OC_CNUMORD AS NRO_OC, OC_CCODPRO AS RUC, CONVERT(VARCHAR, OC_DFECDOC, 103) AS FECHA, OC_CRAZSOC AS PROVEEDOR, OC_CTIPORD AS TIP, 
                  OC_CCODMON AS MON, CASE WHEN oc_ccodmon = 'MN' THEN oc_nimpMN ELSE oc_nimpus END AS IMPORTE, OC_CSITORD AS SIT,
                      (SELECT TG_CDESCRI
                       FROM      RSFACCAR_HISTORICO.dbo.AL0001TABL
                       WHERE   (TG_CCOD = '31') AND (RSFACCAR_HISTORICO.dbo.CO0001MOVC.OC_CSITORD = TG_CCLAVE)) AS ESTADO, OC_CCOTIZA AS COTIZA
FROM     RSFACCAR_HISTORICO.dbo.CO0001MOVC


-- SELECT * FROM VIEW_OC_TOTAL WHERE YEAR(FECHA) >2017