USE MODELADOR
GO

create VIEW VIEW_PO_PARTIDA
AS 
SELECT DISTINCT 
PAR.PO, PAR.CCT, CCT.TELA + CCT.COLOR + CCT.COMBI AS TELA, CCT.PARTIDA, PAR.ubi, PAR.KGS, 
PO105.CAN0 + PO105.CAN1 + PO105.CAN2 + PO105.CAN3 + PO105.CAN4 + PO105.CAN5 + PO105.CAN6 + PO105.CAN7 + PO105.CAN8 + PO105.CAN9 AS QTY105, 
PAR.CANT, POS.OFI, POS.CLI, 
POS.NOM, PO105.COLOR, POS.CODEST, POS.ESTCLI, POS.TEMPORADA, POS.DESTEM
FROM         CCTELA				AS CCT 
INNER JOIN   PO_PARTIDA			AS PAR ON CCT.CCT = PAR.CCT 
INNER JOIN   [PO-DETA]	AS PO105 ON PAR.PO = PO105.PO AND PAR.ubi = PO105.UBI
INNER JOIN   VIEW_POS   AS POS ON POS.PO=PAR.PO 