ALTER VIEW VIEW_OFIS
AS
SELECT OFI, CLI, NOM, COTI, CANT, CAST(FOT AS IMAGE) AS FOT, CON, CODEST, EDO, ESTCLI, DESEST, CGEN, DGEN, TPRE, DPRE, CART, FOB, PROTO, VER, TNT, TEMPO, 
                  DESTEM
FROM     (SELECT DISTINCT 
        OO.CODIGO AS OFI, OO.CLIENTE AS CLI, CL.NOMBRE AS NOM, PP.COTIZACION AS COTI, OO.CANTIDAD AS CANT, CAST(ES.FOTO AS VARBINARY) AS FOT, 
        ES.CONTENIDO AS CON, OO.CODEST, OO.ESTADO AS EDO, ES.ESTCLI, ES.DESCRIPCION AS DESEST, dbo.GENEROS.GENERO AS CGEN, 
        dbo.GENEROS.DESCRIPCION AS DGEN, dbo.TIPPRENDA.TIPO AS TPRE, dbo.TIPPRENDA.DESCRIPCION AS DPRE, ES.CODARTICULO AS CART, CC.FOB, 
        PR.PROTO, PR.VERSION AS VER, CASE WHEN nn.OFI IS NULL THEN '' ELSE '*' END AS TNT, PR.TEMPORADA AS TEMPO, TM.DESCRIPCION AS DESTEM
FROM      dbo.CLIENTE AS CL INNER JOIN
        dbo.OFIS AS OO ON CL.CODIGO = OO.CLIENTE INNER JOIN
        dbo.ESTILOS AS ES ON OO.CLIENTE = ES.CLIENTE AND OO.CODEST = ES.CODEST INNER JOIN
        dbo.GENEROS ON ES.GENERO = dbo.GENEROS.GENERO INNER JOIN
        dbo.TIPPRENDA ON ES.TIPOPRENDA = dbo.TIPPRENDA.TIPO LEFT OUTER JOIN
        dbo.POS AS PP INNER JOIN
        dbo.COTIZACION AS CC ON PP.COTIZACION = CC.COTIZACION INNER JOIN
        dbo.PROTOS AS PR ON CC.PROTO = PR.PROTO AND CC.VERSION = PR.VERSION ON OO.CODIGO = PP.OFI LEFT OUTER JOIN
        dbo.TEMPORADAS AS TM ON TM.CLIENTE = CL.CODIGO AND TM.CODIGO = PR.TEMPORADA FULL OUTER JOIN
        dbo.EXPLOSION_TELA AS nn ON OO.CODIGO = nn.OFI) AS CCC
